### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  id: IFileTypeSettingsConverter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,System.String)
  langs:
  - csharp
  - vb
  name: IFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nInterface which should be implemented by File Types supporting conversion from XML to Json settings and vice versa\n"
  syntax:
    content: public interface IFileTypeSettingsConverter
    content.vb: Public Interface IFileTypeSettingsConverter
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,System.String)
  id: ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertXmlToJson(ISettingsBundle, String)
  nameWithType: IFileTypeSettingsConverter.ConvertXmlToJson(ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nConverts from an Xml settings object to a Json settings object\n"
  syntax:
    content: ISettingsBundle ConvertXmlToJson(ISettingsBundle xmlSettingsBundle, string fileTypeConfigurationId)
    parameters:
    - id: xmlSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: xml settings bundle
    - id: fileTypeConfigurationId
      type: System.String
      description: fileTypeConfigurationId
    return:
      type: Sdl.Core.Settings.ISettingsBundle
      description: IJsonSettingsBundle with settings from passed in xmlSettingsBundle
    content.vb: Function ConvertXmlToJson(xmlSettingsBundle As ISettingsBundle, fileTypeConfigurationId As String) As ISettingsBundle
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  id: ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertXmlToJson(ISettingsBundle, ISettingsBundle, String)
  nameWithType: IFileTypeSettingsConverter.ConvertXmlToJson(ISettingsBundle, ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nConverts from XML to JSON passing in both settings bundles and fileTypeConfigurationId\n"
  syntax:
    content: void ConvertXmlToJson(ISettingsBundle xmlSettingsBundle, ISettingsBundle jsonSettingsBundle, string fileTypeConfigurationId)
    parameters:
    - id: xmlSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: XML settings bundle
    - id: jsonSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: JSON settings bundle
    - id: fileTypeConfigurationId
      type: System.String
      description: fileTypeConfigurationId
    content.vb: Sub ConvertXmlToJson(xmlSettingsBundle As ISettingsBundle, jsonSettingsBundle As ISettingsBundle, fileTypeConfigurationId As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,System.String)
  id: ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertJsonToXml(ISettingsBundle, String)
  nameWithType: IFileTypeSettingsConverter.ConvertJsonToXml(ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nConverts from a Json settings object to an Xml settings object\n"
  syntax:
    content: ISettingsBundle ConvertJsonToXml(ISettingsBundle jsonSettingsBundle, string fileTypeConfigurationId)
    parameters:
    - id: jsonSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: json settings bundle
    - id: fileTypeConfigurationId
      type: System.String
      description: fileTypeConfigurationId
    return:
      type: Sdl.Core.Settings.ISettingsBundle
      description: A populated ISettingsBundle with settings from passed in jsonSettingsBundle
    content.vb: Function ConvertJsonToXml(jsonSettingsBundle As ISettingsBundle, fileTypeConfigurationId As String) As ISettingsBundle
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  id: ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertJsonToXml(ISettingsBundle, ISettingsBundle, String)
  nameWithType: IFileTypeSettingsConverter.ConvertJsonToXml(ISettingsBundle, ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: "\nConverts from Json to XML passing in both settings bundles and fileTypeConfigurationId\n"
  syntax:
    content: void ConvertJsonToXml(ISettingsBundle jsonSettingsBundle, ISettingsBundle xmlSettingsBundle, string fileTypeConfigurationId)
    parameters:
    - id: jsonSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: JSON settings bundle
    - id: xmlSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: XML settings bundle
    - id: fileTypeConfigurationId
      type: System.String
      description: fileTypeConfigurationId
    content.vb: Sub ConvertJsonToXml(jsonSettingsBundle As ISettingsBundle, xmlSettingsBundle As ISettingsBundle, fileTypeConfigurationId As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson
  isExternal: true
  name: ConvertXmlToJson
  nameWithType: IFileTypeSettingsConverter.ConvertXmlToJson
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertXmlToJson
- uid: Sdl.Core.Settings.ISettingsBundle
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml
  isExternal: true
  name: ConvertJsonToXml
  nameWithType: IFileTypeSettingsConverter.ConvertJsonToXml
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.ConvertJsonToXml
